# Generated by Django 4.2 on 2024-02-05 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_recruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('title', models.FileField(null=True, upload_to='')),
                ('salary', models.FloatField(max_length=40)),
                ('image', models.FileField(upload_to='')),
                ('decscription', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('sliklls', models.CharField(max_length=255)),
                ('creation_date', models.DateField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.recruiter')),
            ],
        ),
    ]
