# Generated by Django 4.2 on 2024-02-06 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='sliklls',
            new_name='skills',
        ),
    ]
