# Generated by Django 4.2 on 2024-02-06 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_rename_sliklls_job_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='decscription',
            new_name='description',
        ),
    ]
